### ISSUE TITLE
Generating content for RTE (TinyMCE) and submit (put generated text into tinymce) empties editor

### ISSUE THREAD

**Issue by remkovb** [Smayke95/Umbraco.OpenAI#2]
Generating content for RTE (TinyMCE) and submit after generating text (put generated text into tinymce) empties editor.

So:
   $scope.model.umbracoProperty.property.value = $scope.generateResponse.text;

This doesn't work for TinyMCE editor

**Comment by Smayke95** [comment]
@remkovb it looks that Umbraco updates changed something for RTE (TinyMCE), because previously this worked.

I made a little fix, so new version 1.0.7 is available to download. 

[fix: RTE (TinyMCE) not updates value after submit](https://github.com/Smayke95/Umbraco.OpenAI/commit/7be88901fc97ce3265a4d4fa381fa93138a138c9)
